---
- hosts: localhost
  connection: local
  vars:
  gather_facts: False
  vars:
    keypair: maven
    instance_type: t2.micro
    security_group:
    image: "ami-0f9fc25dd2506cf6d"
    region: us-east-1
    user_access_key: "xxxxxxxxxxxxxxxxxxxx"
    user_secret_key: "xxxxxxxxxxxxxxxxxx"

  tasks:
    - name: startup new instance
      ec2:
         key_name: "{{ keypair }}"
         groups: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         assign_public_ip: yes
         vpc_subnet_id: "subnet-0b5a55464587680c0"
         aws_access_key: "{{ user_access_key }}"
         aws_secret_key: "{{ user_secret_key }}"
      register: ec2

    - debug:
        var: ec2.instances[0].public_ip
